name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check files
      run: ls -la
    
    - name: Test health endpoint locally
      run: |
        npm install -g serve
        node index.js &
        sleep 10
        curl -f http://localhost:3000/health || exit 1
    
    - name: Build Docker image
      run: docker build -t ece-node-projet .
